services:
  app:
    build:
      context: .
    container_name: job_service_php_app
    environment:
      - APP_ENV=production
      - LOG_LEVEL=info
      - DB_DRIVER=pgsql
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_DATABASE=backend_php_slim_db
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgrespw
      - REDIS_HOST=host.docker.internal
      - REDIS_PORT=6379
      - MESSAGING_ENABLED=true
      - RABBIT_HOST=host.docker.internal
      - RABBIT_PORT=5672
      - RABBIT_USER=guest
      - RABBIT_PASSWORD=guest
      - HEALTH_CHECK_CRON=*/1 * * * *
      - HEALTH_CHECK_ENABLED=true
    extra_hosts:
      - "host.docker.internal:host-gateway"
