sonar.projectKey=backend-php-slim
sonar.projectName=Backend PHP Slim
sonar.projectVersion=1.0.0

sonar.sources=src
sonar.tests=tests
sonar.php.coverage.reportPaths=coverage/clover.xml

# Exclude coverage for specific test utilities or helpers if any
# sonar.coverage.exclusions=src/SomeHelper.php

# Ignore issues with hardcoded credentials or passwords in env files or dev configs
# Ignore false positive for S1185 (Controllers overriding methods for Swagger Annotations)
sonar.issue.ignore.multicriteria=e1,e2,e3
sonar.issue.ignore.multicriteria.e1.ruleKey=php:S2068
sonar.issue.ignore.multicriteria.e1.resourceKey=docker-compose.yml
sonar.issue.ignore.multicriteria.e2.ruleKey=php:S2068
sonar.issue.ignore.multicriteria.e2.resourceKey=.env*
sonar.issue.ignore.multicriteria.e3.ruleKey=php:S1185
sonar.issue.ignore.multicriteria.e3.resourceKey=src/**/*Controller.php

sonar.sourceEncoding=UTF-8
sonar.cpd.exclusions=**/*Controller.php
